### ISSUE TITLE
example config.yml file

### ISSUE THREAD

**Issue by 99snowleopards** [yiqings/HEGnnEnhanceCnn#1]
thank you for releasing this repo! it'd be very helpful if you could add an example `config.yml` file that can be passed to `main.py`

thanks,

**Comment by yiqings** [comment]
@99snowleopards Apologies for the late awareness of this issue. 
Thanks for your suggestion. we have provided two `config.yaml` examples at https://github.com/yiqings/HEGnnEnhanceCnn/tree/master/config. I hope you may find them useful.

**Comment by 99snowleopards** [comment]
thanks so much, @yiqings !
