### ISSUE TITLE
Issue with Missing Scripts in model's init.py Program

### ISSUE THREAD

**Issue by Happygirl1768** [yiqings/HEGnnEnhanceCnn#2]
Dear Github project maintainers,

I have encountered an issue with the init.py program in your repository. Specifically, the following two lines of code: "from .trans_gnn import GCNViT" and "from .resnet_gnn import GCNResNet" cannot be executed because these two scripts are missing from the "model" folder. As a result, the program cannot run as expected.

Could you please provide these missing scripts so that I can continue working on this project? Thank you for your attention and assistance in this matter.

Best regards

**Comment by yiqings** [comment]
@Happygirl1768  Thanks for pointing out the issue. Actually, those two models are not used, hence we have just removed them in the `__init__.py`.
